[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONPATH = "/app"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements-railway.txt"
]

[start]
cmd = "gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --workers 1 --bind 0.0.0.0:$PORT --timeout 120"